@isTest
public class AfterAssignmentTestClass {
    
public static testMethod void validateAssignmentClass() {
          
  Integer a = 5;
    
    opportunityEstimationClass oc = new opportunityEstimationClass();
    oc.EstimationStageMethod();
    
   String reqSkills ='Salesforce Developer;Salesforce Administrator;CPQ Developer;LWC Developer;Salesforce QA Tester;Solution Architect';
   Map<String,Integer> emp = getEmployeeDetailsForScoping.getDetails(reqSkills);
    
    EmployeeQuery eq = new EmployeeQuery('Salesforce Developer', 1 , 'Developer');
          
}
         
}