public class opportunityClass {
    public String Phase;
    public Integer Estimated_hours;
    public Integer Resources;
    public Integer Cost_per_hour;
    public opportunityClass(String Phase, Integer Estimated_hours, Integer Resources, Integer Cost_per_hour)
    {
        this.Phase = Phase;
        this.Estimated_hours = Estimated_hours;
        this.Resources = Resources;
        this.Cost_per_hour = Cost_per_hour;
    }
}